version: '3'
services:
  db:
    image: postgres:latest
    container_name: kaimono-db
    ports:
      - 5433:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: steg
      POSTGRES_PASSWORD: U2p7wsaC
      POSTGRES_DATABASE: kaimono
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: kaimono-db
    restart: always
    user: root
    networks:
      - kaimono-network

  backend:
    image: kaimono-backend
    build: ./
    ports: 
      - "5000:5000"
    networks:
      - kaimono-network
    depends_on:
      - "db"

networks:
  kaimono-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24